### ISSUE TITLE
Fairy Gone

### ISSUE THREAD

**Issue by Wladaas** [gagizagi/Axolotl-GO#18]
Hello we were using your bot in our fansub to get know when episode was released but seems there is no fairy gone. Will you add it soon ?

**Comment by gagizagi** [comment]
Everything is automatic. I don't know why fairy gone didn't get added twice. If episode 3 won't be added tomorrow I'll maybe look into it.

**Comment by Wladaas** [comment]
Alright thanks but i mean there is no code for fairy gone to get notifications

**Comment by gagizagi** [comment]
39dcf32aa4b49a67c9e5ac8bfb060bbb97f610c5

There was a bug with any anime also released in 360p not getting detected. Fixed now.
